volumes:
  spark-shared:
  pgdata:
  python:
  airflow-logs:
  airflow-plugins:
  airflow-dags:


services:
  spark-master:
    build: ./docker
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PYSPARK_PYTHON=/app/.venv/bin/python
      - PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python
    ports:
      - "8080:8080" # Web UI
      - "7077:7077" # Spark master port
      - "4040:4040" # Spark Application UI
      - "2222:22"   # SSH
    networks:
      - spark-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - spark-shared:/home/root
      - python:/app

  spark-worker-1:
    build: ./docker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=/app/.venv/bin/python
      - PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - spark-network
    volumes:
      - spark-shared:/home/root
      - python:/app

  spark-worker-2:
    build: ./docker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=/app/.venv/bin/python
      - PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - spark-network
    volumes:
      - spark-shared:/home/root
      - python:/app

  # MinIO (S3-compatible storage)
  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - '9000:9000'  # Changed from 9000 to avoid HDFS conflict
      - '9001:9001'
    #   volumes:
    #     - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - spark-network
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ma_base
      POSTGRES_USER: mon_user
      POSTGRES_PASSWORD: mon_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - spark-network

  streamlit-page:
    build:
      context: Docker
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-page
    ports:
      - "8501:8501"
      - "2223:22"
    networks:
      - spark-network
    volumes:
      - spark-shared:/home/root
      - python:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow:
    build:
      context: ./docker
      dockerfile: Dockerfile.airflow
    container_name: airflow
    depends_on:
      - postgres
      - minio
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://mon_user:mon_password@postgres:5432/ma_base
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=true
      - AIRFLOW_UID=50000
      - AIRFLOW_GID=0
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - airflow-dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
      - airflow-plugins:/opt/airflow/plugins
      - ./ex01_data_retrieval:/opt/airflow/ex01_data_retrieval
      - ./ex02_data_ingestion:/opt/airflow/ex02_data_ingestion
      - ./ex03_sql_table_creation:/opt/airflow/ex03_sql_table_creation
      - ./ex05_ml_prediction_service:/opt/airflow/ex05_ml_prediction_service
      - spark-shared:/home/root
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:8080"
    networks:
      - spark-network
    command: standalone
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  spark-network:
    driver: bridge