[project]
name = "ex05-ml-prediction-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.35.91",
    "numpy>=2.4.2",
    "pyspark>=4.1.1",
    "streamlit>=1.53.1",
]
